
package com.a03.recieveaudio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecieveMultiplayerImplService", targetNamespace = "http://recieveaudio.a03.com/", wsdlLocation = "http://localhost:8080/AudioLocalTest/recievemulti?wsdl")
public class RecieveMultiplayerImplService
    extends Service
{

    private final static URL RECIEVEMULTIPLAYERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECIEVEMULTIPLAYERIMPLSERVICE_EXCEPTION;
    private final static QName RECIEVEMULTIPLAYERIMPLSERVICE_QNAME = new QName("http://recieveaudio.a03.com/", "RecieveMultiplayerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/AudioLocalTest/recievemulti?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECIEVEMULTIPLAYERIMPLSERVICE_WSDL_LOCATION = url;
        RECIEVEMULTIPLAYERIMPLSERVICE_EXCEPTION = e;
    }

    public RecieveMultiplayerImplService() {
        super(__getWsdlLocation(), RECIEVEMULTIPLAYERIMPLSERVICE_QNAME);
    }

    public RecieveMultiplayerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECIEVEMULTIPLAYERIMPLSERVICE_QNAME, features);
    }

    public RecieveMultiplayerImplService(URL wsdlLocation) {
        super(wsdlLocation, RECIEVEMULTIPLAYERIMPLSERVICE_QNAME);
    }

    public RecieveMultiplayerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECIEVEMULTIPLAYERIMPLSERVICE_QNAME, features);
    }

    public RecieveMultiplayerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecieveMultiplayerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecieveMultiplayerImpl
     */
    @WebEndpoint(name = "RecieveMultiplayerImplPort")
    public RecieveMultiplayerImpl getRecieveMultiplayerImplPort() {
        return super.getPort(new QName("http://recieveaudio.a03.com/", "RecieveMultiplayerImplPort"), RecieveMultiplayerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecieveMultiplayerImpl
     */
    @WebEndpoint(name = "RecieveMultiplayerImplPort")
    public RecieveMultiplayerImpl getRecieveMultiplayerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://recieveaudio.a03.com/", "RecieveMultiplayerImplPort"), RecieveMultiplayerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECIEVEMULTIPLAYERIMPLSERVICE_EXCEPTION!= null) {
            throw RECIEVEMULTIPLAYERIMPLSERVICE_EXCEPTION;
        }
        return RECIEVEMULTIPLAYERIMPLSERVICE_WSDL_LOCATION;
    }

}
