
package com.a03.recievemulti;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.a03.game.MaoriNumbers;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecieveMultiplayerImpl", targetNamespace = "http://recievemulti.a03.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecieveMultiplayerImpl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recieveAudio", targetNamespace = "http://recievemulti.a03.com/", className = "com.a03.recievemulti.RecieveAudio")
    @ResponseWrapper(localName = "recieveAudioResponse", targetNamespace = "http://recievemulti.a03.com/", className = "com.a03.recievemulti.RecieveAudioResponse")
    @Action(input = "http://recievemulti.a03.com/RecieveMultiplayerImpl/recieveAudioRequest", output = "http://recievemulti.a03.com/RecieveMultiplayerImpl/recieveAudioResponse")
    public boolean recieveAudio(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<MaoriNumbers> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
