
package com.a03.gamehistory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GameHistoryUpdaterImplService", targetNamespace = "http://gamehistory.a03.com/", wsdlLocation = "http://webapp-171011083620.azurewebsites.net:80/Audio/history?wsdl")
public class GameHistoryUpdaterImplService
    extends Service
{

    private final static URL GAMEHISTORYUPDATERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GAMEHISTORYUPDATERIMPLSERVICE_EXCEPTION;
    private final static QName GAMEHISTORYUPDATERIMPLSERVICE_QNAME = new QName("http://gamehistory.a03.com/", "GameHistoryUpdaterImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webapp-171011083620.azurewebsites.net:80/Audio/history?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMEHISTORYUPDATERIMPLSERVICE_WSDL_LOCATION = url;
        GAMEHISTORYUPDATERIMPLSERVICE_EXCEPTION = e;
    }

    public GameHistoryUpdaterImplService() {
        super(__getWsdlLocation(), GAMEHISTORYUPDATERIMPLSERVICE_QNAME);
    }

    public GameHistoryUpdaterImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMEHISTORYUPDATERIMPLSERVICE_QNAME, features);
    }

    public GameHistoryUpdaterImplService(URL wsdlLocation) {
        super(wsdlLocation, GAMEHISTORYUPDATERIMPLSERVICE_QNAME);
    }

    public GameHistoryUpdaterImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMEHISTORYUPDATERIMPLSERVICE_QNAME, features);
    }

    public GameHistoryUpdaterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GameHistoryUpdaterImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameHistoryUpdaterImpl
     */
    @WebEndpoint(name = "GameHistoryUpdaterImplPort")
    public GameHistoryUpdaterImpl getGameHistoryUpdaterImplPort() {
        return super.getPort(new QName("http://gamehistory.a03.com/", "GameHistoryUpdaterImplPort"), GameHistoryUpdaterImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameHistoryUpdaterImpl
     */
    @WebEndpoint(name = "GameHistoryUpdaterImplPort")
    public GameHistoryUpdaterImpl getGameHistoryUpdaterImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gamehistory.a03.com/", "GameHistoryUpdaterImplPort"), GameHistoryUpdaterImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMEHISTORYUPDATERIMPLSERVICE_EXCEPTION!= null) {
            throw GAMEHISTORYUPDATERIMPLSERVICE_EXCEPTION;
        }
        return GAMEHISTORYUPDATERIMPLSERVICE_WSDL_LOCATION;
    }

}
