
package com.a03.gamehistory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetGameHistoryImplService", targetNamespace = "http://gamehistory.a03.com/", wsdlLocation = "http://webapp-171011083620.azurewebsites.net:80/Audio/gethist?wsdl")
public class GetGameHistoryImplService
    extends Service
{

    private final static URL GETGAMEHISTORYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETGAMEHISTORYIMPLSERVICE_EXCEPTION;
    private final static QName GETGAMEHISTORYIMPLSERVICE_QNAME = new QName("http://gamehistory.a03.com/", "GetGameHistoryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webapp-171011083620.azurewebsites.net:80/Audio/gethist?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETGAMEHISTORYIMPLSERVICE_WSDL_LOCATION = url;
        GETGAMEHISTORYIMPLSERVICE_EXCEPTION = e;
    }

    public GetGameHistoryImplService() {
        super(__getWsdlLocation(), GETGAMEHISTORYIMPLSERVICE_QNAME);
    }

    public GetGameHistoryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETGAMEHISTORYIMPLSERVICE_QNAME, features);
    }

    public GetGameHistoryImplService(URL wsdlLocation) {
        super(wsdlLocation, GETGAMEHISTORYIMPLSERVICE_QNAME);
    }

    public GetGameHistoryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETGAMEHISTORYIMPLSERVICE_QNAME, features);
    }

    public GetGameHistoryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetGameHistoryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetGameHistoryImpl
     */
    @WebEndpoint(name = "GetGameHistoryImplPort")
    public GetGameHistoryImpl getGetGameHistoryImplPort() {
        return super.getPort(new QName("http://gamehistory.a03.com/", "GetGameHistoryImplPort"), GetGameHistoryImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetGameHistoryImpl
     */
    @WebEndpoint(name = "GetGameHistoryImplPort")
    public GetGameHistoryImpl getGetGameHistoryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gamehistory.a03.com/", "GetGameHistoryImplPort"), GetGameHistoryImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETGAMEHISTORYIMPLSERVICE_EXCEPTION!= null) {
            throw GETGAMEHISTORYIMPLSERVICE_EXCEPTION;
        }
        return GETGAMEHISTORYIMPLSERVICE_WSDL_LOCATION;
    }

}
