
package com.a03.gamehistory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetGameHistoryImpl", targetNamespace = "http://gamehistory.a03.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetGameHistoryImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGameHistory", targetNamespace = "http://gamehistory.a03.com/", className = "com.a03.gamehistory.GetGameHistory")
    @ResponseWrapper(localName = "getGameHistoryResponse", targetNamespace = "http://gamehistory.a03.com/", className = "com.a03.gamehistory.GetGameHistoryResponse")
    @Action(input = "http://gamehistory.a03.com/GetGameHistoryImpl/getGameHistoryRequest", output = "http://gamehistory.a03.com/GetGameHistoryImpl/getGameHistoryResponse")
    public String getGameHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
