
package com.a03.stats;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.a03.game.Stats;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatsHandlerImpl", targetNamespace = "http://stats.a03.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StatsHandlerImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.a03.stats.Stats
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStats", targetNamespace = "http://stats.a03.com/", className = "com.a03.stats.GetStats")
    @ResponseWrapper(localName = "getStatsResponse", targetNamespace = "http://stats.a03.com/", className = "com.a03.stats.GetStatsResponse")
    @Action(input = "http://stats.a03.com/StatsHandlerImpl/getStatsRequest", output = "http://stats.a03.com/StatsHandlerImpl/getStatsResponse")
    public Stats getStats(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
