
package com.a03.stats;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatsHandlerImplService", targetNamespace = "http://stats.a03.com/", wsdlLocation = "http://webapp-171011083620.azurewebsites.net:80/Audio/stats?wsdl")
public class StatsHandlerImplService
    extends Service
{

    private final static URL STATSHANDLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATSHANDLERIMPLSERVICE_EXCEPTION;
    private final static QName STATSHANDLERIMPLSERVICE_QNAME = new QName("http://stats.a03.com/", "StatsHandlerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webapp-171011083620.azurewebsites.net:80/Audio/stats?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATSHANDLERIMPLSERVICE_WSDL_LOCATION = url;
        STATSHANDLERIMPLSERVICE_EXCEPTION = e;
    }

    public StatsHandlerImplService() {
        super(__getWsdlLocation(), STATSHANDLERIMPLSERVICE_QNAME);
    }

    public StatsHandlerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATSHANDLERIMPLSERVICE_QNAME, features);
    }

    public StatsHandlerImplService(URL wsdlLocation) {
        super(wsdlLocation, STATSHANDLERIMPLSERVICE_QNAME);
    }

    public StatsHandlerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATSHANDLERIMPLSERVICE_QNAME, features);
    }

    public StatsHandlerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatsHandlerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatsHandlerImpl
     */
    @WebEndpoint(name = "StatsHandlerImplPort")
    public StatsHandlerImpl getStatsHandlerImplPort() {
        return super.getPort(new QName("http://stats.a03.com/", "StatsHandlerImplPort"), StatsHandlerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatsHandlerImpl
     */
    @WebEndpoint(name = "StatsHandlerImplPort")
    public StatsHandlerImpl getStatsHandlerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://stats.a03.com/", "StatsHandlerImplPort"), StatsHandlerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATSHANDLERIMPLSERVICE_EXCEPTION!= null) {
            throw STATSHANDLERIMPLSERVICE_EXCEPTION;
        }
        return STATSHANDLERIMPLSERVICE_WSDL_LOCATION;
    }

}
