
package com.a03.multiplayer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GameInfoImplService", targetNamespace = "http://multiplayer.a03.com/", wsdlLocation = "http://localhost:8080/AudioLocalTest/gameinf?wsdl")
public class GameInfoImplService
    extends Service
{

    private final static URL GAMEINFOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GAMEINFOIMPLSERVICE_EXCEPTION;
    private final static QName GAMEINFOIMPLSERVICE_QNAME = new QName("http://multiplayer.a03.com/", "GameInfoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/AudioLocalTest/gameinf?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMEINFOIMPLSERVICE_WSDL_LOCATION = url;
        GAMEINFOIMPLSERVICE_EXCEPTION = e;
    }

    public GameInfoImplService() {
        super(__getWsdlLocation(), GAMEINFOIMPLSERVICE_QNAME);
    }

    public GameInfoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMEINFOIMPLSERVICE_QNAME, features);
    }

    public GameInfoImplService(URL wsdlLocation) {
        super(wsdlLocation, GAMEINFOIMPLSERVICE_QNAME);
    }

    public GameInfoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMEINFOIMPLSERVICE_QNAME, features);
    }

    public GameInfoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GameInfoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameInfoImpl
     */
    @WebEndpoint(name = "GameInfoImplPort")
    public GameInfoImpl getGameInfoImplPort() {
        return super.getPort(new QName("http://multiplayer.a03.com/", "GameInfoImplPort"), GameInfoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameInfoImpl
     */
    @WebEndpoint(name = "GameInfoImplPort")
    public GameInfoImpl getGameInfoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://multiplayer.a03.com/", "GameInfoImplPort"), GameInfoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMEINFOIMPLSERVICE_EXCEPTION!= null) {
            throw GAMEINFOIMPLSERVICE_EXCEPTION;
        }
        return GAMEINFOIMPLSERVICE_WSDL_LOCATION;
    }

}
