
package com.a03.multiplayer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GameInfoImpl", targetNamespace = "http://multiplayer.a03.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GameInfoImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userExists", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.UserExists")
    @ResponseWrapper(localName = "userExistsResponse", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.UserExistsResponse")
    @Action(input = "http://multiplayer.a03.com/GameInfoImpl/userExistsRequest", output = "http://multiplayer.a03.com/GameInfoImpl/userExistsResponse")
    public boolean userExists(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentGames", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.GetCurrentGames")
    @ResponseWrapper(localName = "getCurrentGamesResponse", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.GetCurrentGamesResponse")
    @Action(input = "http://multiplayer.a03.com/GameInfoImpl/getCurrentGamesRequest", output = "http://multiplayer.a03.com/GameInfoImpl/getCurrentGamesResponse")
    public String getCurrentGames(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGameStats", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.GetGameStats")
    @ResponseWrapper(localName = "getGameStatsResponse", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.GetGameStatsResponse")
    @Action(input = "http://multiplayer.a03.com/GameInfoImpl/getGameStatsRequest", output = "http://multiplayer.a03.com/GameInfoImpl/getGameStatsResponse")
    public String getGameStats(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
