
package com.a03.multiplayer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NextMultiplayerLevelImpl", targetNamespace = "http://multiplayer.a03.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NextMultiplayerLevelImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resumeGame", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.ResumeGame")
    @ResponseWrapper(localName = "resumeGameResponse", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.ResumeGameResponse")
    @Action(input = "http://multiplayer.a03.com/NextMultiplayerLevelImpl/resumeGameRequest", output = "http://multiplayer.a03.com/NextMultiplayerLevelImpl/resumeGameResponse")
    public String resumeGame(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nextMultiplayerLevel", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.NextMultiplayerLevel")
    @ResponseWrapper(localName = "nextMultiplayerLevelResponse", targetNamespace = "http://multiplayer.a03.com/", className = "com.a03.multiplayer.NextMultiplayerLevelResponse")
    @Action(input = "http://multiplayer.a03.com/NextMultiplayerLevelImpl/nextMultiplayerLevelRequest", output = "http://multiplayer.a03.com/NextMultiplayerLevelImpl/nextMultiplayerLevelResponse")
    public String nextMultiplayerLevel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
