
package com.a03.leaderboard;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetLeaderboardImpl", targetNamespace = "http://leaderboard.a03.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetLeaderboardImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLeaderBoardInfo", targetNamespace = "http://leaderboard.a03.com/", className = "com.a03.leaderboard.GetLeaderBoardInfo")
    @ResponseWrapper(localName = "getLeaderBoardInfoResponse", targetNamespace = "http://leaderboard.a03.com/", className = "com.a03.leaderboard.GetLeaderBoardInfoResponse")
    @Action(input = "http://leaderboard.a03.com/GetLeaderboardImpl/getLeaderBoardInfoRequest", output = "http://leaderboard.a03.com/GetLeaderboardImpl/getLeaderBoardInfoResponse")
    public String getLeaderBoardInfo();

}
