
package com.a03.recieveaudio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecieveImplService", targetNamespace = "http://recieveaudio.a03.com/", wsdlLocation = "http://webapp-171011083620.azurewebsites.net:80/Audio/webservice?wsdl")
public class RecieveImplService
    extends Service
{

    private final static URL RECIEVEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECIEVEIMPLSERVICE_EXCEPTION;
    private final static QName RECIEVEIMPLSERVICE_QNAME = new QName("http://recieveaudio.a03.com/", "RecieveImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webapp-171011083620.azurewebsites.net:80/Audio/webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECIEVEIMPLSERVICE_WSDL_LOCATION = url;
        RECIEVEIMPLSERVICE_EXCEPTION = e;
    }

    public RecieveImplService() {
        super(__getWsdlLocation(), RECIEVEIMPLSERVICE_QNAME);
    }

    public RecieveImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECIEVEIMPLSERVICE_QNAME, features);
    }

    public RecieveImplService(URL wsdlLocation) {
        super(wsdlLocation, RECIEVEIMPLSERVICE_QNAME);
    }

    public RecieveImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECIEVEIMPLSERVICE_QNAME, features);
    }

    public RecieveImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecieveImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecieveImpl
     */
    @WebEndpoint(name = "RecieveImplPort")
    public RecieveImpl getRecieveImplPort() {
        return super.getPort(new QName("http://recieveaudio.a03.com/", "RecieveImplPort"), RecieveImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecieveImpl
     */
    @WebEndpoint(name = "RecieveImplPort")
    public RecieveImpl getRecieveImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://recieveaudio.a03.com/", "RecieveImplPort"), RecieveImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECIEVEIMPLSERVICE_EXCEPTION!= null) {
            throw RECIEVEIMPLSERVICE_EXCEPTION;
        }
        return RECIEVEIMPLSERVICE_WSDL_LOCATION;
    }

}
