
package com.a03.recieveaudio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.a03.game.MaoriNumbers;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecieveImpl", targetNamespace = "http://recieveaudio.a03.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecieveImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playAudio", targetNamespace = "http://recieveaudio.a03.com/", className = "com.a03.recieveaudio.PlayAudio")
    @ResponseWrapper(localName = "playAudioResponse", targetNamespace = "http://recieveaudio.a03.com/", className = "com.a03.recieveaudio.PlayAudioResponse")
    @Action(input = "http://recieveaudio.a03.com/RecieveImpl/playAudioRequest", output = "http://recieveaudio.a03.com/RecieveImpl/playAudioResponse")
    public boolean playAudio(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<MaoriNumbers> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
