
package com.a03.newlevel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NewLevel1to9Impl", targetNamespace = "http://newlevel.a03.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewLevel1To9Impl {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "newGame1to9")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newGame1to9", targetNamespace = "http://newlevel.a03.com/", className = "com.a03.newlevel.NewGame1To9")
    @ResponseWrapper(localName = "newGame1to9Response", targetNamespace = "http://newlevel.a03.com/", className = "com.a03.newlevel.NewGame1To9Response")
    @Action(input = "http://newlevel.a03.com/NewLevel1to9Impl/newGame1to9Request", output = "http://newlevel.a03.com/NewLevel1to9Impl/newGame1to9Response")
    public int newGame1To9(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "new1to9")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "new1to9", targetNamespace = "http://newlevel.a03.com/", className = "com.a03.newlevel.New1To9")
    @ResponseWrapper(localName = "new1to9Response", targetNamespace = "http://newlevel.a03.com/", className = "com.a03.newlevel.New1To9Response")
    @Action(input = "http://newlevel.a03.com/NewLevel1to9Impl/new1to9Request", output = "http://newlevel.a03.com/NewLevel1to9Impl/new1to9Response")
    public int new1To9(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
