
package com.a03.newlevel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NewLevel1to9ImplService", targetNamespace = "http://newlevel.a03.com/", wsdlLocation = "http://webapp-171011083620.azurewebsites.net:80/Audio/newlevel1to9service?wsdl")
public class NewLevel1To9ImplService
    extends Service
{

    private final static URL NEWLEVEL1TO9IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NEWLEVEL1TO9IMPLSERVICE_EXCEPTION;
    private final static QName NEWLEVEL1TO9IMPLSERVICE_QNAME = new QName("http://newlevel.a03.com/", "NewLevel1to9ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webapp-171011083620.azurewebsites.net:80/Audio/newlevel1to9service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEWLEVEL1TO9IMPLSERVICE_WSDL_LOCATION = url;
        NEWLEVEL1TO9IMPLSERVICE_EXCEPTION = e;
    }

    public NewLevel1To9ImplService() {
        super(__getWsdlLocation(), NEWLEVEL1TO9IMPLSERVICE_QNAME);
    }

    public NewLevel1To9ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEWLEVEL1TO9IMPLSERVICE_QNAME, features);
    }

    public NewLevel1To9ImplService(URL wsdlLocation) {
        super(wsdlLocation, NEWLEVEL1TO9IMPLSERVICE_QNAME);
    }

    public NewLevel1To9ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEWLEVEL1TO9IMPLSERVICE_QNAME, features);
    }

    public NewLevel1To9ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewLevel1To9ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NewLevel1To9Impl
     */
    @WebEndpoint(name = "NewLevel1to9ImplPort")
    public NewLevel1To9Impl getNewLevel1To9ImplPort() {
        return super.getPort(new QName("http://newlevel.a03.com/", "NewLevel1to9ImplPort"), NewLevel1To9Impl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewLevel1To9Impl
     */
    @WebEndpoint(name = "NewLevel1to9ImplPort")
    public NewLevel1To9Impl getNewLevel1To9ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://newlevel.a03.com/", "NewLevel1to9ImplPort"), NewLevel1To9Impl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEWLEVEL1TO9IMPLSERVICE_EXCEPTION!= null) {
            throw NEWLEVEL1TO9IMPLSERVICE_EXCEPTION;
        }
        return NEWLEVEL1TO9IMPLSERVICE_WSDL_LOCATION;
    }

}
