
package com.a03.newlevel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NewLevel1to99ImplService", targetNamespace = "http://newlevel.a03.com/", wsdlLocation = "http://webapp-171011083620.azurewebsites.net:80/Audio/newlevel1to99service?wsdl")
public class NewLevel1To99ImplService
    extends Service
{

    private final static URL NEWLEVEL1TO99IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NEWLEVEL1TO99IMPLSERVICE_EXCEPTION;
    private final static QName NEWLEVEL1TO99IMPLSERVICE_QNAME = new QName("http://newlevel.a03.com/", "NewLevel1to99ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webapp-171011083620.azurewebsites.net:80/Audio/newlevel1to99service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEWLEVEL1TO99IMPLSERVICE_WSDL_LOCATION = url;
        NEWLEVEL1TO99IMPLSERVICE_EXCEPTION = e;
    }

    public NewLevel1To99ImplService() {
        super(__getWsdlLocation(), NEWLEVEL1TO99IMPLSERVICE_QNAME);
    }

    public NewLevel1To99ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEWLEVEL1TO99IMPLSERVICE_QNAME, features);
    }

    public NewLevel1To99ImplService(URL wsdlLocation) {
        super(wsdlLocation, NEWLEVEL1TO99IMPLSERVICE_QNAME);
    }

    public NewLevel1To99ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEWLEVEL1TO99IMPLSERVICE_QNAME, features);
    }

    public NewLevel1To99ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewLevel1To99ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NewLevel1To99Impl
     */
    @WebEndpoint(name = "NewLevel1to99ImplPort")
    public NewLevel1To99Impl getNewLevel1To99ImplPort() {
        return super.getPort(new QName("http://newlevel.a03.com/", "NewLevel1to99ImplPort"), NewLevel1To99Impl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewLevel1To99Impl
     */
    @WebEndpoint(name = "NewLevel1to99ImplPort")
    public NewLevel1To99Impl getNewLevel1To99ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://newlevel.a03.com/", "NewLevel1to99ImplPort"), NewLevel1To99Impl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEWLEVEL1TO99IMPLSERVICE_EXCEPTION!= null) {
            throw NEWLEVEL1TO99IMPLSERVICE_EXCEPTION;
        }
        return NEWLEVEL1TO99IMPLSERVICE_WSDL_LOCATION;
    }

}
