
package com.a03.newlevel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NewLevel1to99Impl", targetNamespace = "http://newlevel.a03.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewLevel1To99Impl {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "new1to99")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "new1to99", targetNamespace = "http://newlevel.a03.com/", className = "com.a03.newlevel.New1To99")
    @ResponseWrapper(localName = "new1to99Response", targetNamespace = "http://newlevel.a03.com/", className = "com.a03.newlevel.New1To99Response")
    @Action(input = "http://newlevel.a03.com/NewLevel1to99Impl/new1to99Request", output = "http://newlevel.a03.com/NewLevel1to99Impl/new1to99Response")
    public int new1To99(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "newGame1to99")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newGame1to99", targetNamespace = "http://newlevel.a03.com/", className = "com.a03.newlevel.NewGame1To99")
    @ResponseWrapper(localName = "newGame1to99Response", targetNamespace = "http://newlevel.a03.com/", className = "com.a03.newlevel.NewGame1To99Response")
    @Action(input = "http://newlevel.a03.com/NewLevel1to99Impl/newGame1to99Request", output = "http://newlevel.a03.com/NewLevel1to99Impl/newGame1to99Response")
    public int newGame1To99(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
